import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { client } from '@/lib/client'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ blog, cat }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Category</h1>
          <ul>
            {cat.map((cat) => (
              <li key={cat.id}>{cat.name}: {cat.desc}</li>
            ))}
          </ul>
        </div>
        <div>
          <h1>Blog</h1>
          <ul>
            {blog.map((blog) => (
              <li>
                <Link key={blog.id} href={`/blog/${blog.id}`}>{blog.title}</Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const blogData = await client.get({ endpoint: 'blogs' });
  const categoryData = await client.get({ endpoint: 'categories' });

  return {
    props: {
      blog: blogData.contents,
      cat: categoryData.contents,
    },
  };
}